..  _Coveralls:         https://coveralls.io/
..  _GitHub:            https://github.com/
..  _PyPI:              http://pypi.python.org/
..  _`PyPI Live`:       http://pypi.python.org/pypi?%3Aaction=register_form 
..  _`PyPI Test`:       http://testpypi.python.org/pypi?%3Aaction=register_form
..  _PyLit6:            http://www.pylit.org
..  _reStructuredText:  http://docutils.sourceforge.net/rst.html
..  _TravisCI:          https://travis-ci.org/ 
